### ISSUE TITLE
How to configure diferent internal and external port?

### ISSUE THREAD

**Issue by xGuIInE** [ofekp/TinyUPnP#50]
I don´t know if it´s possible to select 443 for internal router port and 9005 for the external port.

**Comment by ofekp** [comment]
Hey, currently the package does not support that.

You can look here to understand why:
https://github.com/ofekp/TinyUPnP/blob/master/src/TinyUPnP.cpp#L54-L63

It does require a change, overloading the API method with a new method that will accept the two ports (instead of only one LISTEN_PORT) and then passing it to all the needed places.
If you're interested in making it that will be awesome and will speed things up.

As a side note, I suggest not using the port 443 as it is used for SSL. Actually, you should not use any root port in the range (1..1024) as it is bad practice.

**Comment by xGuIInE** [comment]
Thanks for the answer!
It would be very useful! When i´ll have free time I will try to implement this feature request!

I´m using 443 because it´s a https server port haha. 

Greetings =)

**Comment by ofekp** [comment]
Awesome!
If you need any help, let me know. I will happily review :)

**Comment by sebosfato** [comment]
Any progress on this?

**Comment by ofekp** [comment]
Please stay tuned for this [PR](https://github.com/ofekp/TinyUPnP/pull/74)
You will be able to configure different internal and external ports by using the correct method `addPortMappingConfig`.

**Comment by sebosfato** [comment]
its already working! with the changes i described.. . also i forgot there was another place to change it was where it call NewInternal … one of them is wrong… should look like this 

strcat_P(body_tmp, PSTR("\"><NewRemoteHost></NewRemoteHost><NewExternalPort>"));
    sprintf(integer_string, "%d", rule_ptr->externalPort);
    strcat_P(body_tmp, integer_string);
    strcat_P(body_tmp, PSTR("</NewExternalPort><NewProtocol>"));
    strcat_P(body_tmp, rule_ptr->protocol.c_str());
    strcat_P(body_tmp, PSTR("</NewProtocol><NewInternalPort>"));
    sprintf(integer_string, "%d", rule_ptr->internalPort);
    strcat_P(body_tmp, integer_string);
    strcat_P(body_tmp, PSTR("</NewInternalPort><NewInternalClient>"));
    IPAddress ipAddress = (rule_ptr->internalAddr == ipNull) ? WiFi.localIP() : rule_ptr->internalAddr;
    strcat_P(body_tmp, ipAddress.toString().c_str());
    strcat_P(body_tmp, PSTR("</NewInternalClient><NewEnabled>1</NewEnabled><NewPortMappingDescription>"));
    strcat_P(body_tmp, rule_ptr->devFriendlyName.c_str());
    strcat_P(body_tmp, PSTR("</NewPortMappingDescription><NewLeaseDuration>"));
    sprintf(integer_string, "%d", rule_ptr->leaseDuration);
    strcat_P(body_tmp, integer_string);
    strcat_P(body_tmp, PSTR("</NewLeaseDuration></u:AddPortMapping></s:Body></s:Envelope>"));
    
    
    for some reason it was pointing all to the same external… now its correct

**Comment by ofekp** [comment]
Great, glad you managed to make it work.
I will close this once we merge the PR I mentioned as it also includes these changes and a few more fixes that will make the package more stable.

**Comment by ofekp** [comment]
I am closing this since this PR https://github.com/ofekp/TinyUPnP/pull/74 adds support to configure the internal and external ports separately for each rule (please note it does require calling the correct method to do that).
