### ISSUE TITLE
Gateway info is not valid

### ISSUE THREAD

**Issue by felipefpires** [ofekp/TinyUPnP#58]
Hello, i'm trying to stablish an open port with the tinyupnp with my esp32 but it doesn't work no more and im not able to find out what is going on. I hope you can help me.
My guess is that the root of the problem is that the info sent by the router is not being understood by the esp, any thougths?

![1](https://user-images.githubusercontent.com/46383925/77250345-2dbadf00-6c26-11ea-9978-ad155bf27d74.PNG)

**Comment by ofekp** [comment]
Hey can you explain what happened please?

**Comment by felipefpires** [comment]
I managed to make it work, it happens that the router that i was using was
not sending back the msearch and so the data required to make the upnp work
wasn't being received.
Now the problem is that even though the upnp is working, the router is
secondary in my network and the main one does not allow the routing.
The upnp solution might not work for my project, i have to find a more
universal solution for my project as it should work in any given home
network.
If you have any ideas of what i could use i would apreciate.

Nevertheless, thank you for your attention.

Felipe F.

Em dom, 29 de mar de 2020 17:54, Ofek <notifications@github.com> escreveu:

**Comment by ofekp** [comment]
If you have more than one router in your setup, and only one is connected to the modem, you need to enable UPnP only in the modem connected router and turn off UPnP in any other router (other routers will also have DHCP disabled), this should work for both WiFi and ethernet connected devices.
