### ISSUE TITLE
Implementation for knowing what all services are present on the network

### ISSUE THREAD

**Issue by Gungeoneer** [ofekp/TinyUPnP#61]
Hi, I am using your library along with the Arduino for ESP8266 SDK. I was working with the example SimpleServer from your library. However, I am unable to see my other SSDP Devices in the logs from the example. Do I need to make any changes in the code to be able to do that?

**Comment by ofekp** [comment]
This is probably what you'll have to change, I am only looking for IGD devices
https://github.com/ofekp/TinyUPnP/blob/master/src/TinyUPnP.cpp#L529

You can consult with a [branch](https://github.com/ofekp/TinyUPnP/pull/53/files#diff-9a08934cec8ffa5b3c2325ef2595ae1dR21-R30) I currently have but not merged to understand how to fire multiple M-SEARCH queries or you can use a wide deviceType with a single M-SEARCH query (all). Note that it is better to narrow it as much as you can. You can narrow based on the response you get from the device which should include the correct deviceType.

**Comment by Gungeoneer** [comment]
I did try that branch as you have suggested. I am using the [SSDP example from the Arudino SDK for ESP8266 ](https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266SSDP/examples/SSDP/SSDP.ino) which registers a device on the network as a Philips Hue Clone. I am able to see that device as well as another device on in the Networks folder on Windows 10. However, I am unable to find them in the debug logs.

Given how the branch is not yet merged, is this feature still a work in progress? I am looking to implement a SSDP listener so I can get a list of any devices on the network. If I can understand what you have suggested correctly, I can fire a single M-SEARCH query for all devices and it will list down whatever devices are on the network?

**Comment by ofekp** [comment]
Instead of using the branch (I am not sure I will ever merge that), can you try changing the line 
https://github.com/ofekp/TinyUPnP/blob/master/src/TinyUPnP.cpp#L529
to 
`strcat_P(body_tmp, PSTR("ST: ssdp:all\r\n\r\n"));`

**Comment by Gungeoneer** [comment]
Thanks for your continued guidance and assistance!

Okay, I have tried what you suggested. I have also removed the [`return false`](https://github.com/ofekp/TinyUPnP/blob/master/src/TinyUPnP.cpp#L601) which stops the program from proceeding if any device other than an Internet Gateway Device is found.

However, despite this I am only able to see communication between the device and the Router. At the end I get the message saying that all ports and devices were discovered without my device ever showing up. For additional reference, my device has the following property: 

`SSDP.setDeviceType("upnp:rootdevice");`

Are there any additional changes that would be required to show such types of devices?

**Comment by ofekp** [comment]
> Okay, I have tried what you suggested. I have also removed the return false which stops the program from proceeding if any device other than an Internet Gateway Device is found.

Nice, I actually forgot about that one :)

Can you try to replace the [same line](https://github.com/ofekp/TinyUPnP/blob/master/src/TinyUPnP.cpp#L529) with this:
strcat_P(body_tmp, PSTR("ST: upnp:rootdevice\r\n\r\n"));

Please also make sure you are running the code you intend to run. You can add a compilation error on purpose and compile to see if your changes are actually being used.

By seeing communication with the router, you mean you can see in the debug logs the response to the M-SEARCH message which contains, among other headers, the Location header, is this correct?

For the device you are setting up with
`SSDP.setDeviceType("upnp:rootdevice");`
Is it listening on port 1900 UDP?

Do you have access to a linux machine? Can you use something like [this ](http://infotinks.com/find-upnp-devices-network-ex-readydlna-upnp-routers/) maybe? to see if the device responds?
I have not tried it myself, if you find a better way to check for all upnp devices in your network please let me know what you found.

**Comment by Gungeoneer** [comment]
> Do you have access to a linux machine? Can you use something like this maybe? to see if the device responds?

Through `gssdp`, I am able to see all the devices in my network on Linux. I can also selectively target specific device types to show only the ones that I need. 

> For the device you are setting up with
> SSDP.setDeviceType("upnp:rootdevice");
> Is it listening on port 1900 UDP?

Yes, it is listening on port 1900 

> I have not tried it myself, if you find a better way to check for all upnp devices in your network please let me know what you found.

I think the tutorial you linked for gssdp is the best way to discover all devices, thanks a lot for the help :)

**Comment by ofekp** [comment]
I would like to understand if you were able to find the device using TinyUPnP, if so what did you do.
If you no longer need it, can I close the issue?

**Comment by Gungeoneer** [comment]
Hey ofekp, I really appreciate your quick responses and all the help which you have provided to me.  I wasn't able to reply in the past few days due to some work issues. 

> If you no longer need it, can I close the issue?

Yes, I would like for you to close the issue, I have found the solution to my problem.

> BTW, I found that there are two places where I filter based on the assumption that I the response should be received from an IGD device, did you remove both of them when trying the package?
waitForUnicastResponseToMSearch - if (remoteIP != gatewayIP) {
waitForUnicastResponseToMSearch - if (strstr(responseBuffer, INTERNET_GATEWAY_DEVICE) == NULL) {

Yes, I did remove both of these as well as what we had previously discussed in order to make sure all the devices were visible. It works like a charm now :)

> I would like to understand if you were able to find the device using TinyUPnP, if so what did you do.

If you would like to see exactly the parts that I changed, I can make a pull request which you can leave as it is or I can send you a diff file with my changes.

**Comment by ofekp** [comment]
Awesome, I am happy it worked :) and NP
I would love to see what you change for the purpose of being able to help in the future, I might also incorporate this into the code with a flag or simply reference to this change from the README should someone need this in the future. So, yeah, if you can please share either a diff or a PR 👍 
Thank you.

**Comment by Gungeoneer** [comment]
Couldn't upload a diff file directly so here is a text file which you can change the extension of:
[ChangesForAllDevices.txt](https://github.com/ofekp/TinyUPnP/files/4515557/ChangesForAllDevices.txt)

**Comment by ofekp** [comment]
Beautiful, thank you :) I will find a way to make it available for others in the README or via a flag 👍 
Closing this for now.

**Comment by ofekp** [comment]
FYI, I just pushed this [PR](https://github.com/ofekp/TinyUPnP/commit/dcb7ef3162ea1445cb3c84c676d880062d02275b) which gives a dedicated method to list all SSDP devices based on on the diff you provided (but as a function).
I also provided an example to show how to use it.
Thank you.
