### ISSUE TITLE
ERROR: Invalid router info, cannot continue

### ISSUE THREAD

**Issue by JeanRenier** [ofekp/TinyUPnP#62]
Dear, 
Trying to make the example "SimpleServerESP32" to work on a ESP32 DevKit.  It looks as if the router is not cooperating, see text below.  
Tried on two different routers: a Docsis 3.0 (modem router) and a (old) TL-WR340G (WiFi router), both with uPnP enabled.  
I am probably doing something wrong, any clues?  
Many thanks, Jean. 

PS.  the line with "print mappings configured & current: " and following is my attempt to have some more info out of the router by inserting a tinyUPnP.printPortMappingConfig(); and a  tinyUPnP.printAllPortMappings(); statement.

..........
Connected to testingRemoteHF
IP address: 192.168.1.101
Testing WiFi connection for [192.168.1.101] ==> GOOD
Testing internet connection ==> GOOD
isGatewayInfoValid [0.0.0.0] port [0] path [] actionPort [0] actionPath [] serviceTypeName []
Gateway info is not valid

Sending M-SEARCH to [239.255.255.250] Port [1900]
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 5
ST: urn:schemas-upnp-org:device:InternetGatewayDevice:1

M-SEARCH sent
Timeout expired while waiting for the gateway router to respond to M-SEARCH message
ERROR: Invalid router info, cannot continue

UPnP done
MDNS responder started
HTTP server started
print mappings configured & current: 
TinyUPnP configured port mappings:
0.   testESP32                     192.168.1.101     1237   1237   TCP    36000  

isGatewayInfoValid [0.0.0.0] port [0] path [] actionPort [0] actionPath [] serviceTypeName []
Gateway info is not valid
Invalid router info, cannot continue
Updating port mapping
Testing WiFi connection for [192.168.1.101] ==> GOOD
Testing internet connection ==> GOOD
isGatewayInfoValid [0.0.0.0] port [0] path [] actionPort [0] actionPath [] serviceTypeName []
Gateway info is not valid

**Comment by ofekp** [comment]
are you using the master branch latest commit?
I am aware of a problem in the latest commit I made.
If you do, please use stable version https://github.com/ofekp/TinyUPnP/tree/v3.1.4 instead.
I will fix the issue in the latest code version in master branch in the next couple of days.

**Comment by JeanRenier** [comment]
Dear,
Using the latest branch commit (fixESP32bug) now.  Works as expected in the small test sketch now.  Many thanks, have still to integrate it within my application. 
For some reason the packets can not be reflected in the same access router (even though this was possible with static port forwarding), i.o.w. the client and the server have to be each on a distinct access router.  This is obviously a router thing rather than a uPnP thing, it makes testing a bit harder, but is in fact no problem.
All the best.

**Comment by ofekp** [comment]
Awesome, NP. Thanks for closing.
